site_name: Ethical Pentesting with EVE-NG
site_description: Bachelor's Thesis - Virtual labs for cybersecurity training
site_author: Eloi Egea Rada
site_url: https://TheEgea.github.io/TFG
repo_url: https://github.com/TheEgea/TFG
edit_uri: edit/main/docs/web/docs/

theme:
  name: material
  language: en
  palette:
    - scheme: default
      primary: red
      accent: red
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.top
    - content.code.copy
    - content.code.annotate
    - content.tabs
    - navigation.sections
    - navigation.indexes
    - search.suggest
    - search.highlight

nav:
  - Home: index.md
  - Thesis Documentation:
      - Memory: assets/Temp.md
      - Feasibility Study: assets/official_Documents/feasibility.md
  - Basic Configuration:
      - Router (VyOS): assets/init_configs/Router.md
      - Firewall (pfSense): assets/init_configs/Firewall.md
  - EVE-NG Labs:
      - LAB1 – Network Setup:
          - Overview: labs/lab1/index.md
          - Router: labs/lab1/router.md
          - Server: labs/lab1/server.md
          - PC1: labs/lab1/pc1.md
          - Firewall: labs/lab1/firewall.md
#  - Pentest Labs:
#      - Reconnaissance: labs/recon.md
#      - Web Vulns: labs/web-vulns.md
#      - Priv Esc: labs/priv-esc.md
#      - Crypto: labs/crypto.md

plugins:
  - search

markdown_extensions:
  - abbr
  - attr_list
  - pymdownx.snippets
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
