set interfaces ethernet eth0 address '192.168.1.2/24'
set interfaces ethernet eth0 description 'LAN-to-pfSense'
set interfaces ethernet eth1 address '10.10.1.1/24'
set interfaces ethernet eth1 description 'Zone-A-ServerA'
set interfaces ethernet eth2 address '10.10.2.1/24'
set interfaces ethernet eth2 description 'Zone-B-ServerB'
set interfaces ethernet eth3 address '10.10.3.1/24'
set interfaces ethernet eth3 description 'Zone-C-ServerC'
set interfaces ethernet eth4 address '10.10.4.1/24'
set interfaces ethernet eth4 description 'Zone-Defense-Defender'
set protocols static route 0.0.0.0/0 next-hop 192.168.1.1
set system host-name 'vyos-lab4'
set system login user vyos authentication plaintext-password 'vyos'
set system login user vyos level 'admin'
set service ssh port '22'
